url: https://veganismosemduvida.github.io
name: Veganismo, sem dúvida!
description: Um espaço sobre&nbsp;veganismo para&nbsp;veganos, futuros&nbsp;veganos&nbsp;e&nbsp;curiosos
baseurl:
exclude:
  - .jekyll-cache
